name: CI
on: push
jobs:
  test:
    name: "version: ${{ matrix.version != '' && matrix.version || 'empty'}}, os: ${{ matrix.os }}, stable: ${{ matrix.stable }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ !matrix.stable }}
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        os:
          - ubuntu-18.04
          - ubuntu-latest
        version:
          - "" # Test empty tag
          - placeos-1.2105.3
          - placeos-1.2107.4
          - placeos-1.2108.4
          - placeos-1.2109.0
          - placeos-1.2109.1
        include:
          - version: nightly
            stable: false
            os: ubuntu-18.04
          - version: nightly
            stable: false
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test initialization
        run: ./placeos start --verbose
        env:
          PLACEOS_TAG: ${{ matrix.version }}
          PLACE_EMAIL: robot@place.tech
          PLACE_PASSWORD: development
      - name: Test initialization, with unset PLACEOS_TAG
        if: ${{ matrix.version == '' }} # Testing an empty tag
        run: |
          docker-compose down --volumes &> /dev/null
          rm .env.*
          ./placeos start --verbose
        env:
          PLACE_EMAIL: robot@place.tech
          PLACE_PASSWORD: development
      - name: Upload logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.os }}-${{ matrix.version }}-${{ github.sha }}
          path: .logs/*.log
      - name: List service statuses
        run: docker-compose ps
      - name: Check API is reachable
        continue-on-error: true
        run: curl --retry 10 --insecure -fsSL https://localhost:8443/api/engine/v2
      - name: Test raw `docker-compose`
        run: docker-compose down
